language: go
sudo: true
go: 
     - 1.9.x

notifications:
    email:
        recipients: 
            - hwchiu@linkernetworks.com
            - cwlin@linkernetworks.com
        on_success: change
before_install:
    - sudo apt-get install -y git build-essential openvswitch-switch
    - go get -u github.com/kardianos/govendor
    - go get -u github.com/pierrre/gotestcover
    - docker run -d -p 2379:2379 --name etcd quay.io/coreos/etcd:v3.2  /usr/local/bin/etcd  --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379
install: 
    - govendor sync
script:
    - sudo -E env PATH=$PATH TEST_ETCD=1 gotestcover -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
    - bash <(curl -s https://codecov.io/bash)
