language: go
sudo: true
go: 
     - 1.9.x

notifications:
    email:
        recipients: 
            - hwchiu@linkernetworks.com
            - cwlin@linkernetworks.com
        on_success: change
before_install:
    - sudo apt-get install -y git build-essential openvswitch-switch
    - go get -u github.com/kardianos/govendor
    - docker run -d -p 8001:8001 -p 4001:4001 coreos/etcd -name etcd-node1
install: 
    - govendor sync
script:
    - sudo -E env PATH=$PATH go test -coverprofile=coverage.txt -covermode=atomic ./ovs
after_success:
    - bash <(curl -s https://codecov.io/bash)
